
server:
  port: 9001

spring:
    application:
      name: turbine


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true


turbine:
  app-config: CONSUMER1,CLIENT02

  aggregator:
        cluster-config: default
