server:
  port: 3003

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        # http://localhost:3003/client1/get 路由到 -> http://PROD-CLIENT-01/client1/get
        - id: client9001
          uri: lb://PROD-CLIENT-01
          predicates:
            - Path=/client1/**
            # 查询参数带有（name=wuquan&age=18）
#            - Query=name,wuquan
#            - Query=age,18
          filters:
            # 添加参数过滤器
            - AddRequestParameter=name,wuquan
            #熔断整合,需要加入hystrix依赖
#            - Hystrix=hystrix
#            - name: Hystrix    #hystrix \u7684commandName
#                args:
#                  name:
#                  fallbackUri: forward:/fallback1

        - id: client9002
          uri: lb://PROD-CLIENT-02
          predicates:
            - Path=/client2/**



eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true



