server:
  port: 8081
# http://localhost:8081/application/prod/main
# http://localhost:8081/main/application-prod.yml
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties
spring:
  application:
    name: config
  profiles:
    #本地配置文件
    active: native
  cloud:
    config:
      server:
        #本地配置文件
        bootstrap: true
        native:
          search-locations: file:F:\config
        #\u8FDC\u7A0B\u914D\u7F6E
  rabbitmq:
    username: admin
    password: admin
    port: 5672
    host: localhost
#        git:
#          uri: https://github.com/www-321/cloud-config.git
#          password: hero.wuquan5
#          username: www-321
#          default-label: main


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true



management:
  endpoints:
    web:
      exposure:
        # 不能用"" 双引号
        include: '*'