server:
  port: 7001


spring:
  application:
    name: consumer1

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true

# ribbon 超时全局配置
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 7000
  ###指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 7000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

# feign 开启支持hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      # feign客户端调用超时配置
      default:
        readTimeout: 4000
        connectTimeout: 4000
      # 指定客户端服务实例
#      CLIENT02:
#        readTimeout: 11000
#        connectTimeout: 11000
logging:
  level:
    com.cloud.eurekaclientconsumer7001.feign: debug
hystrix:
  command:
    #局部关闭熔断
#    UserFeignApi#getUser(String,String):
#      enabled: false
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000
    default:
      # 全局开启
#     circuitBreaker:
#       enabled: true
     execution:
       isolation:
         #  隔离策略
         strategy: THREAD

         # 全局超时配置
         thread:
           timeoutInMilliseconds: 8000
  #  接口级别
  # hystrix.command.UserRemoteClient#getUser(Long).execution.isolation.thread.timeoutInMilliseconds = 300


management:
  endpoint:
    health:
      show-details: always



