server:
  port: 7001


spring:
  application:
    name: consumer1

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true

# ribbon 超时全局配置
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000

logging:
  level:
    com.cloud.eurekaclientconsumer7001.feign: debug

hystrix:
  command:
   default:
    execution:
     isolation:
       #  隔离策略
       strategy: THREAD








