server:
  port: 8766

spring:
  application:
    name: eureka-server2
  security:

    user:
      name: admin
      password: 123456
eureka:
  client:

#          register-with-eureka: false
#          fetch-registry: false
          service-url:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8762/eureka/
  instance:

          instance-id: ${spring.application.name}:${server.port}
          prefer-ip-address: true


