

server:
  port: 9001


spring:
#  sleuth:
#    sampler:
#      probability: 1
#    web:
#      client:
#        enabled: true
#  zipkin:
#    base-url: http://localhost:9411/
  application:
    name: prod-client-01


logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug
#    com.cloud.springframework.sleuth: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true