
server:
  port: 9002


spring:
  application:
    name: prod-client-02


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8762/eureka/
  instance:

    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true



logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug
#    com.cloud.springframework.sleuth: debug